name: Get Custom Field from Issue

on:
  workflow_dispatch: # Manually triggered workflow

jobs:
  fetch-custom-field:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Query Custom Field from Project Item
      id: get-custom-field
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        # Define the GraphQL query
        $query = @"
        query GetCustomField($projectId: ID!, $itemId: ID!, $fieldName: String!) {
          node(id: $itemId) {
            ... on ProjectV2Item {
              id
              fieldValues(first: 100) {
                nodes {
                  field {
                    ... on ProjectV2Field {
                      name
                    }
                  }
                  ... on ProjectV2ItemFieldValueText {
                    text
                  }
                  ... on ProjectV2ItemFieldValueSingleSelect {
                    name
                  }
                }
              }
            }
          }
        }
        "@

        # Set variables (replace with actual IDs or dynamically fetch them)
        $projectItemId = "PVTI_lAHOAAFgjc4AuhQQzgVwqTw"
        $fieldName = "Status"

        # Prepare the payload
        $payload = @{
          query = $query
          variables = @{
            itemId = $projectItemId
            fieldName = $fieldName
          }
        } | ConvertTo-Json -Depth 10

        # Call the GitHub GraphQL API
        $headers = @{
          Authorization = "Bearer $env:GITHUB_TOKEN"
          "Content-Type" = "application/json"
        }
        $response = Invoke-RestMethod -Uri "https://api.github.com/graphql" -Method POST -Headers $headers -Body $payload

        # Check if the response is valid
        if (-not $response) {
          Write-Error "Error: No response from API."
          exit 1
        }

        # Extract the custom field value
        $value = $response.data.node.fieldValues.nodes |
          Where-Object { $_.field.name -eq $fieldName } |
          ForEach-Object { $_.text -or $_.name }

        if (-not $value) {
          Write-Error "Error: Custom field '$fieldName' not found or has no value."
          exit 1
        }

        Write-Output "Custom Field Value: $value"
        Write-Output "custom_field_value=$value" >> $env:GITHUB_ENV

    - name: Use the Custom Field Value
      shell: pwsh
      run: |
        Write-Output "The custom field value is $env:custom_field_value"
