- name: Test jq Query
  shell: pwsh
  run: |
    OUTPUT=$(gh api graphql -f query='
    query getIssueData {
      node(id: "PVT_kwHOAAFgjc4AuhQQ") {
        ... on ProjectV2 {
          items(last: 20) {
            nodes {
              id
              content {
                ... on Issue {
                  title
                  state
                  id
                  assignees(first: 10) {
                    nodes {
                      login
                    }
                  }
                }
              }
              fieldValues(first: 20) {
                nodes {
                  ... on ProjectV2ItemFieldSingleSelectValue {
                    field {
                      ... on ProjectV2SingleSelectField {
                        name
                      }
                    }
                    name
                    id
                  }
                }
              }
            }
          }
        }
      }
    }')
    echo "$OUTPUT" | jq -r '.data.node.items.nodes[] | select(.content.id == "I_kwDOKdDuds6jrP5m") | .fieldValues.nodes[] | select(.field.name == "Status") | .name'
