name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:   
  issues:
    types:
      - edited
      - reopened
      - opened
jobs:
  update_date_fixed:
    runs-on: [self-hosted, windows, x64]
    permissions:
      issues: write
      contents: read
    steps:
      id: auth
      env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      echo "Issue number: ${{ github.event.issue.number }}"
      echo "Action: ${{ github.event.action }}"
