name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:   
  issues:
    types:
      - edited
      - reopened
      - opened
    runs-on: [self-hosted,windows,x64]
    steps:
      id: auth
      env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      echo "Issue number: ${{ github.event.issue.number }}"
      echo "Action: ${{ github.event.action }}"
