name: Update "Date Fixed" Field on Status Change

on:
  issues:
    types:
      - labeled

jobs:
  update_date_fixed:
    runs-on: [self-hosted, windows, x64]
    permissions:
      issues: write
      contents: read
    steps:
      - name: Print all issue details including custom fields

        run: |

          echo "Issue Title: ${{ github.event.issue.title }}"
          field_value = ${{ github.event.issue.labels[0].name }}"
          echo "Custom field value: ${{ github.event.issue.labels[0].name }}"
          echo ${{field_value}}
          echo "${{ toJson(github.event.issue.labels[0].name) }}"
          
      # Step 1: Check for Status is "Ready for QA"
      - name: Check if Status is "Ready for QA"

        id: check_status
        uses: actions/github-script@v6
        with:
          script: |
           const label = context.payload.label;
           const labelName = label ? label.name : null;
           const status = context.payload.status;

           console.log(status);
           
            if (labelName === "Ready for QA") {
              console.log("Label 'Ready for QA' detected.");
              core.setOutput("status_ready_for_qa", "true");
            } else {
              console.log("Label 'Ready for QA' not detected.");
              core.setOutput("status_ready_for_qa", "false");
            }
      

      # Step 2: Update "Date Fixed" Field with Today's Date
      - name: Update "Date Fixed" Custom Field
      #  if: steps.check_status.outputs.status_ready_for_qa == 'true'
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            mutation UpdateProjectField($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: String!) {
              updateProjectV2ItemFieldValue(
                input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: {text: $value}}
              ) {
                projectV2Item {
                  id
                }
              }
            }
          variables: |
            {
              "projectId": "PVT_kwHOAAFgjc4AuhQQ",
              "itemId": "${{ github.event.issue.node_id }}",
              "fieldId": "PVTF_lAHOAAFgjc4AuhQQzglGg2Y",
              "value": "${{ steps.date.outputs.today_date }}"
            }

      # Step 3: Get Today's Date
      - name: Set Today's Date (Windows)
        id: date
        run: |
          $today = Get-Date -Format yyyy-MM-dd
          echo "today_date=$today" >> $env:GITHUB_ENV
        shell: pwsh

